/**
 * Metallic Text Effect
 */

const mumaker = require('mumaker');
const config = require('../../config');

module.exports = {
  name: 'metallic',
  aliases: [],
  category: 'textmaker',
  description: 'Create metallic text effect',
  usage: '.metallic <text>',

  async execute(sock, msg, args, extra = {}) {
    const chatId = extra.from || msg.key.remoteJid;
    const reply = extra.reply || (t => sock.sendMessage(chatId, { text: t }, { quoted: msg }));
    const text = args.join(' ').trim();
    if (!text) return reply('❌ Usage: .metallic <text>');

    try {
      await sock.sendPresenceUpdate('composing', chatId).catch(() => {});
      const result = await mumaker.ephoto('https://en.ephoto360.com/impressive-decorative-3d-metal-text-effect-798.html', text);
      if (!result || !result.image) throw new Error('No image received');

      await sock.sendMessage(chatId, {
        image: { url: result.image },
        caption: `✨ Generated by ${config.botName}`
      }, { quoted: msg });
    } catch (err) {
      console.error('[metallic] error', err);
      await reply('❌ Failed to generate image.');
    } finally {
      try { await sock.sendPresenceUpdate('paused', chatId); } catch (e) {}
    }
  }
};

